name: Docker Image CI (OnPremise)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., 3.0.0)'
        required: true
        type: string
      push_image:
        description: 'Push image to Docker Hub?'
        required: true
        type: boolean
        default: false

env:
  REGISTRY: docker.io
  IMAGE_NAME: conplementag/vsts-agent

jobs:
  build:
    name: Build Docker Image
    runs-on: [self-hosted, OnPremise]
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: false
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}
        outputs: type=docker,dest=/tmp/image-${{ github.event.inputs.tag }}.tar
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-${{ github.event.inputs.tag }}
        path: /tmp/image-${{ github.event.inputs.tag }}.tar
        retention-days: 7

  push:
    name: Push Docker Image
    runs-on: [self-hosted, OnPremise]
    needs: build
    if: ${{ github.event.inputs.push_image == 'true' }}
    permissions:
      contents: read
      packages: write

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image-${{ github.event.inputs.tag }}
        path: /tmp
        
    - name: Load Docker image
      run: docker load --input /tmp/image-${{ github.event.inputs.tag }}.tar
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Push Docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}
